name: Build
on: [push]

jobs:
  build:
    name: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: step-1
        uses: docker://alpine:latest
        run: |
          echo "Hello, World?"
          touch test
      - name: step-2
        uses: docker://ubuntu:latest
        run: |
          ls -l
