name: Build
on: [push]

jobs:
  build:
    name: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to Google Container Registry
        run: docker login -u _json_key -p $(echo $GCP_SERVICE_ACCOUNT) gcr.io
      - name: Build Image
        run: docker build . -t gcr.io/synchthia-network/actions-test:latest
      - name: Push Image
        run: docker push gcr.io/synchthia-network/actions-test:latest
