name: Build
on: [push]

jobs:
  build:
    name: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://alpine:latest
        run: |
          echo "Hello, World?"
          touch test
      - uses: docker://ubuntu:latest
        run: |
          ls -l
