name: Build
on: [push]

jobs:
  build:
    name: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: switch-alpine
        uses: docker://alpine:latest
      - name: step-1
        run: |
          echo "Hello, World?"
          touch test

      - name: switch-ubuntu
        uses: docker://ubuntu:latest
      - name: step-2
        run: |
          ls -l
